"""empty message

Revision ID: 52b2d27c8435
Revises: 4ae9fd1233b9
Create Date: 2021-04-12 16:54:18.757129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b2d27c8435'
down_revision = '4ae9fd1233b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.NUMERIC(), nullable=True))

    # ### end Alembic commands ###
