"""empty message

Revision ID: 817884277905
Revises: b40d95197a6a
Create Date: 2021-04-14 04:08:07.259111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817884277905'
down_revision = 'b40d95197a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
