"""empty message

Revision ID: f2959880edbf
Revises: 817884277905
Create Date: 2021-04-14 04:54:59.087364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2959880edbf'
down_revision = '817884277905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
